services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: pasdb
      POSTGRES_USER: pas
      POSTGRES_PASSWORD: paspassword
    ports:
      - 5433:5433
    volumes:
      - pg:/var/lib/postgresql/data
volumes:
  pg:






